substitutions:
  name: master-bedroom-curtains
  friendly_name: "Master Bedroom Curtains"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  api_key: !secret master_bedroom_curtains_api_key
  ap_ssid: "Master Bedroom Fallback Hotspot"
  ap_password: !secret master_bedroom_curtains_ap_password
  direction_restore: ALWAYS_OFF

packages:
  curtain_base:
    url: https://github.com/TonyBrobston/esphome-tuya-curtains
    files: [common-curtain.yaml]
    ref: main
    refresh: 1d
